name: test run docker

on: [push]

env:
  TOPIC: monitor
  DB_NAME: monitor
  DB_PASSWORD: test_password

jobs:
  database-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      # run postgresql
      - name: run postgresql
        run: |
          docker run --name postgres -p 5432:5432 -e POSTGRES_PASSWORD=${DB_PASSWORD} -d postgres:latest

      - name: create database
        run: |
          docker exec postgres createdb --username postgres ${DB_NAME}

      # run zookeeper & kafka
      - name: create a network
        run: |
          docker network create kafka-net --driver bridge
      - name: run zookeeper
        run: |
          docker run -d --network kafka-net --name zookeeper -e ALLOW_ANONYMOUS_LOGIN=yes bitnami/zookeeper:latest

      - name: run kafka server
        run: |
          docker run -d --network kafka-net -h kafka --name kafka \
          -e ALLOW_PLAINTEXT_LISTENER=yes \
          -e KAFKA_BROKER_ID=1 \
          -e KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181 \
          -e KAFKA_CFG_LISTENERS=PLAINTEXT://kafka:9092 \
          -e KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092 \
          -p 9092:9092 \
          bitnami/kafka:latest

      - run: docker ps

      - name: create topic
        run: |
          docker run --rm --network kafka-net \
          -e KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181 bitnami/kafka:latest \
          kafka-topics.sh --create --topic ${TOPIC} --replication-factor 1 --partitions 1 --bootstrap-server kafka:9092

      - name: list topic
        run: |
          docker run --rm --network kafka-net \
          -e KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181 bitnami/kafka:latest \
          kafka-topics.sh --list --bootstrap-server kafka:9092

      - name: describe topic
        run: |
          docker run --rm --network kafka-net \
          -e KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181 bitnami/kafka:latest \
          kafka-topics.sh --describe --topic ${TOPIC} --bootstrap-server kafka:9092

      # install packages
      - name: install python packages
        run: |
          apt update
          apt install -y python3-daemon python3-requests python3-psycopg2
          pip3 install pykafka
      
      - run: ls -al